# Generated by Django 4.0.4 on 2022-05-23 18:14

import data_push.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=30)),
                ('app_secret', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=30)),
                ('http_method', models.CharField(choices=[(data_push.models.HttpChoice['GET'], 1), (data_push.models.HttpChoice['POST'], 2), (data_push.models.HttpChoice['PATCH'], 3), (data_push.models.HttpChoice['PUT'], 4), (data_push.models.HttpChoice['DELETE'], 5)], max_length=10)),
                ('headers', models.CharField(max_length=30)),
                ('acc_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_push.account')),
            ],
        ),
    ]
